/**
 * Hosts of URL shorteners, redirect pages and IP loggers. A destination on one
 * of them, or on a subdomain of one, hides its final address from the Safe
 * Browsing check.
 *
 * First-party shorteners that only lead to their owner's own site (youtu.be,
 * amzn.to, aka.ms) are left out: they can't hide where a link goes.
 */
export const URL_SHORTENER_HOSTS: ReadonlySet<string> = new Set([
  '2no.co',
  'adf.ly',
  'bc.vc',
  'bit.do',
  'bit.ly',
  'bitly.com',
  'buff.ly',
  'clck.ru',
  'cutt.ly',
  'dlvr.it',
  'dub.sh',
  'gg.gg',
  'goo.gl',
  'grabify.link',
  'href.li',
  'hubs.la',
  'hubs.ly',
  'ift.tt',
  'iplogger.com',
  'iplogger.org',
  'iplogger.ru',
  'is.gd',
  'j.mp',
  'kutt.it',
  'l.facebook.com',
  'l.instagram.com',
  'l.messenger.com',
  'lm.facebook.com',
  'lnkd.in',
  'ouo.io',
  'out.reddit.com',
  'ow.ly',
  'qrco.de',
  'rb.gy',
  'rebrand.ly',
  'rotf.lol',
  's.id',
  'sh.st',
  'short.gy',
  'shorte.st',
  'shorturl.at',
  't.cn',
  't.co',
  't.ly',
  't.umblr.com',
  'tiny.cc',
  'tiny.one',
  'tinyurl.com',
  'trib.al',
  'u.to',
  'v.gd',
  'vk.cc',
  'wp.me',
  'yip.su',
])
