import crypto from 'crypto'
import { prisma } from '@/lib/prisma'
import { autoGeneratedFooterText, sendEmail } from '@/lib/email'

const TOKEN_TTL_MS = 24 * 60 * 60 * 1000
const RESEND_COOLDOWN_MS = 120 * 1000

export async function sendVerificationEmail(email: string): Promise<boolean> {
  const existing = await prisma.verificationToken.findFirst({ where: { identifier: email } })
  if (existing && Date.now() - existing.createdAt.getTime() < RESEND_COOLDOWN_MS) {
    return false
  }

  const token = crypto.randomBytes(32).toString('hex')

  await prisma.verificationToken.deleteMany({ where: { identifier: email } })
  await prisma.verificationToken.create({
    data: { identifier: email, token, expires: new Date(Date.now() + TOKEN_TTL_MS) },
  })

  const verifyUrl = `${process.env.APP_URL}/api/verify-email?token=${token}`

  await sendEmail({
    to: [email],
    subject: 'Confirm your email address',
    preheader: 'Confirm your email to finish setting up your account.',
    content: `
      <h1 style="margin:0 0 16px;font-size:20px;">Confirm your email</h1>
      <p style="margin:0 0 24px;">Click the button below to confirm your email address and finish setting up your account.</p>
      <p style="margin:0 0 24px;text-align:center;">
        <a href="${verifyUrl}" style="display:inline-block;padding:12px 24px;background-color:#111827;color:#ffffff;text-decoration:none;border-radius:6px;">Confirm email</a>
      </p>
      <p style="margin:0;color:#6b7280;font-size:12px;">Or paste this link into your browser: ${verifyUrl}</p>
    `,
    footerText: autoGeneratedFooterText(),
  })

  return true
}
