import crypto from 'crypto'
import { VerificationTokenType } from '@/generated/client'
import { prisma } from '@/lib/prisma'
import { autoGeneratedFooterText, sendEmail } from '@/lib/email'

const RESEND_COOLDOWN_MS = 120 * 1000

const TOKEN_TTL_MS: Record<VerificationTokenType, number> = {
  EMAIL_VERIFY: 24 * 60 * 60 * 1000,
  EMAIL_CHANGE: 24 * 60 * 60 * 1000,
  PASSWORD_RESET: 20 * 60 * 1000,
}

const LINK_PATH: Record<VerificationTokenType, string> = {
  EMAIL_VERIFY: '/api/verify-email',
  EMAIL_CHANGE: '/api/verify-email',
  PASSWORD_RESET: '/reset-password',
}

const COPY: Record<
  VerificationTokenType,
  { subject: string; preheader: string; heading: string; body: string; cta: string }
> = {
  EMAIL_VERIFY: {
    subject: 'Confirm your email address',
    preheader: 'Confirm your email to finish setting up your account.',
    heading: 'Confirm your email',
    body: 'Click the button below to confirm your email address and finish setting up your account.',
    cta: 'Confirm email',
  },
  EMAIL_CHANGE: {
    subject: 'Confirm your new email address',
    preheader: 'Confirm your new email address to finish updating your account.',
    heading: 'Confirm your new email',
    body: 'Click the button below to confirm this is your new email address. Your account keeps using the old address until you do.',
    cta: 'Confirm email',
  },
  PASSWORD_RESET: {
    subject: 'Reset your password',
    preheader: 'Reset your password — this link expires in 20 minutes.',
    heading: 'Reset your password',
    body: "Click the button below to choose a new password. This link expires in 20 minutes. If you didn't request this, you can safely ignore this email.",
    cta: 'Reset password',
  },
}

export async function sendVerificationEmail(
  email: string,
  type: VerificationTokenType = VerificationTokenType.EMAIL_VERIFY,
): Promise<boolean> {
  const existing = await prisma.verificationToken.findFirst({ where: { identifier: email, type } })
  if (existing && Date.now() - existing.createdAt.getTime() < RESEND_COOLDOWN_MS) {
    return false
  }

  const token = crypto.randomBytes(32).toString('hex')

  await prisma.verificationToken.deleteMany({ where: { identifier: email, type } })
  await prisma.verificationToken.create({
    data: { identifier: email, token, type, expires: new Date(Date.now() + TOKEN_TTL_MS[type]) },
  })

  const verifyUrl = `${process.env.APP_URL}${LINK_PATH[type]}?token=${token}`
  const copy = COPY[type]

  await sendEmail({
    to: [email],
    subject: copy.subject,
    preheader: copy.preheader,
    content: `
      <h1 style="margin:0 0 16px;font-size:20px;">${copy.heading}</h1>
      <p style="margin:0 0 24px;">${copy.body}</p>
      <p style="margin:0 0 24px;text-align:center;">
        <a href="${verifyUrl}" style="display:inline-block;padding:12px 24px;background-color:#111827;color:#ffffff;text-decoration:none;border-radius:6px;">${copy.cta}</a>
      </p>
      <p style="margin:0;color:#6b7280;font-size:12px;">Or paste this link into your browser: ${verifyUrl}</p>
    `,
    footerText: autoGeneratedFooterText(),
  })

  return true
}
