export interface RenderEmailTemplateParams {
  content: string
  preheader?: string
  footerText?: string
}

export function autoGeneratedFooterText(): string {
  return 'This is an automated message, please do not reply.'
}

export function unsubscribeFooterText(url: string): string {
  return `If you no longer wish to receive these emails, <a href="${url}" style="color:#6b7280;text-decoration:underline;">unsubscribe here</a>.`
}

function renderFooter(footerText: string): string {
  if (!footerText) return ''

  return `
    <tr>
      <td style="padding:16px 32px 32px;font-family:Arial,Helvetica,sans-serif;font-size:12px;line-height:18px;color:#9ca3af;text-align:center;">
        ${footerText}
      </td>
    </tr>`
}

function renderHeader(): string {
  return `
    <tr>
      <td style="padding:32px 32px 0;text-align:center;">
        <img src="${process.env.APP_URL}/logo-mail.png" alt="" style="max-height:48px;max-width:240px;" />
      </td>
    </tr>`
}

export function renderEmailTemplate({ content, preheader = '', footerText = '' }: RenderEmailTemplateParams): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
</head>
<body style="margin:0;padding:0;background-color:#f3f4f6;">
  ${preheader ? `<span style="display:none;font-size:1px;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;">${preheader}</span>` : ''}
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f3f4f6;padding:32px 16px;">
    <tr>
      <td align="center">
        <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background-color:#ffffff;border-radius:8px;overflow:hidden;">
          ${renderHeader()}
          <tr>
            <td style="padding:32px;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:22px;color:#111827;">
              ${content}
            </td>
          </tr>
          ${renderFooter(footerText)}
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`
}
